/**
 * Localized labels the preview generates (spec §6.4): note types, task sections, figure
 * and table numbers, and the page's own status strings.
 *
 * Labels are emitted as HTML text by the renderer (not CSS `content`), so assistive
 * technology reads them and DitaCraft's locale applies. English is the fallback for any
 * missing key. Environment-neutral.
 */

export interface Labels {
    note: Record<string, string>;
    hazard: Record<string, string>;
    section: Record<string, string>;
    figure: string;
    table: string;
    relatedInformation: string;
    footnotes: string;
    optional: string;
    required: string;
    option: string;
    description: string;
    type: string;
    value: string;
    ui: Record<string, string>;
    /** Readable names of DITA modules (the part of a class token before "/"), for menus. */
    domains: Record<string, string>;
}

const EN: Labels = {
    note: {
        note: 'Note', tip: 'Tip', fastpath: 'Fastpath', restriction: 'Restriction', important: 'Important',
        remember: 'Remember', attention: 'Attention', caution: 'CAUTION', notice: 'NOTICE', danger: 'DANGER',
        warning: 'WARNING', trouble: 'Trouble', other: 'Note',
    },
    hazard: { danger: 'DANGER', warning: 'WARNING', caution: 'CAUTION', notice: 'NOTICE' },
    section: {
        prereq: 'Before you begin', context: 'About this task', result: 'Results', postreq: 'What to do next',
        tasktroubleshooting: 'Troubleshooting', steptroubleshooting: 'Troubleshooting', condition: 'Condition',
        cause: 'Cause', remedy: 'Remedy', responsibleParty: 'Responsible party',
    },
    figure: 'Figure {0}. ',
    table: 'Table {0}. ',
    relatedInformation: 'Related information',
    footnotes: 'Footnotes',
    optional: 'Optional: ',
    required: 'Required: ',
    option: 'Option',
    description: 'Description',
    type: 'Type',
    value: 'Value',
    ui: {
        problems: '{0} problems',
        oneProblem: '1 problem',
        noProblems: 'No problems',
        fallbackGrammar: 'FALLBACK GRAMMAR',
        waitingForXml: 'Waiting for well-formed XML — line {0}: {1}',
        undeclaredEntities: '{0} undeclared entities',
        filter: 'Filter: {0}',
        noFilter: 'No filter',
        locked: 'Locked to this topic',
        follow: 'Following the active editor',
        showMarkup: 'Show markup',
        hideMarkup: 'Hide markup',
        syncOn: 'Sync: on',
        syncOff: 'Sync: off',
        theme: 'Theme: {0}',
        refresh: 'Refresh',
        openSource: 'Open source',
        previewDitaOt: 'Preview with DITA-OT',
        lock: 'Lock',
        unlock: 'Unlock',
        ctrlClickToOpen: 'Ctrl+click to open',
        fromKey: 'From key "{0}"',
        reusedFrom: 'Reused content from {0}',
        unresolved: 'Unresolved: {0}',
        largeDocument: 'Large document: references are not resolved automatically.',
        emptyPreview: 'Open a DITA topic to preview it.',
        mapNotSupported: 'Maps are previewed with DITA-OT.',
        // Visual editor
        undo: 'Undo',
        redo: 'Redo',
        style: 'Style',
        bold: 'Bold',
        italic: 'Italic',
        underline: 'Underline',
        code: 'Code',
        superscript: 'Superscript',
        subscript: 'Subscript',
        bulletList: 'Bulleted list',
        numberedList: 'Numbered list',
        indent: 'Indent',
        outdent: 'Outdent',
        insert: 'Insert',
        insertMore: 'More elements',
        table: 'Table',
        insertTable: 'Insert table',
        rows: 'Rows',
        rowAbove: 'Insert row above',
        rowBelow: 'Insert row below',
        deleteRow: 'Delete row',
        headerRow: 'Header row on/off',
        columns: 'Columns',
        columnLeft: 'Insert column left',
        columnRight: 'Insert column right',
        deleteColumn: 'Delete column',
        cells: 'Cells',
        mergeRight: 'Merge with the cell on the right',
        mergeDown: 'Merge with the cell below',
        splitCell: 'Split cell',
        line: 'line {0}',
        nextProblem: 'Go to the next problem',
        reused: 'Reused content',
        reuseOpen: 'Open the reused source',
        replaceWithCopy: 'Replace with copy',
        replaceWithCopyTitle: 'Copy the reused content here and remove the reference, to change it in this topic only',
        reuseStale: 'The document changed: try again.',
        reuseFailed: 'Cannot use the reused content: {0}',
        reuseLost: 'The reused element is no longer here.',
        reuseNoFit: 'The copy does not fit here.',
        preview: 'Preview',
        saved: 'All changes are in the document',
        writing: 'Writing…',
        paused: 'Not well-formed XML — line {0}: {1}. Fix it in the source to continue editing.',
        readOnly: 'Read-only',
        notEditable: 'Kept as written: edit it in the source',
        // Properties pane
        properties: 'Properties',
        propertiesEmpty: 'Put the cursor in a DITA topic or map (text or visual editor) to see the attributes of the element there.',
        propertiesNotWellFormed: 'The XML is not well-formed here: fix it to edit attributes.',
        groupIdentity: 'Identity and reuse',
        groupProfiling: 'Profiling',
        groupCommon: 'Common',
        groupElement: 'Element',
        groupArchitecture: 'Architecture',
        notSet: '— not set —',
        defaultValue: 'default: {0}',
        requiredField: 'required',
        fixedField: 'fixed',
        undeclared: 'not declared by the document type',
        remove: 'Remove',
        formattingNoAttributes: 'Formatting such as bold or italic carries no attributes here. Select the enclosing element.',
        readOnlyDocument: 'This document is read-only.',
        documentChanged: 'The document changed: look again and retry.',
        // Context menu
        cut: 'Cut',
        copy: 'Copy',
        paste: 'Paste',
        insertAfter: 'Insert after',
        insertInline: 'Insert inline',
        wrapIn: 'Wrap in',
        changeTo: 'Change to',
        common: 'Common',
        allElements: 'All elements',
        selectElement: 'Select',
        moveUp: 'Move up',
        moveDown: 'Move down',
        unwrapElement: 'Remove tags (keep content)',
        deleteElement: 'Delete',
        attributes: 'Attributes…',
        showInSource: 'Show in source',
        pasteFailed: 'Cannot read the clipboard here: use Ctrl+V.',
        // Images
        image: 'Image',
        imageInText: 'In the text…',
        imageOwnLine: 'On its own line…',
        imageInFigure: 'In a figure…',
        replaceImage: 'Replace image…',
        altText: 'Alternative text…',
        imageAltPrompt: 'Alternative text of the image (read aloud, and shown when the image cannot be)',
        imageAltPlaceholder: 'Describe the image — leave empty for a decorative image',
        imagePickTitle: 'Insert an image',
        imageReplaceTitle: 'Replace the image',
        imagePickLabel: 'Choose',
        imageFilter: 'Images',
        imageSaved: 'Image saved: {0}',
        imageNotHere: 'An image cannot go here.',
        imageFailed: 'Cannot insert the image: {0}',
        // Links
        link: 'Link…',
        changeLink: 'Change link target…',
        openLink: 'Open link target',
        removeLink: 'Remove link',
        linkPickTitle: 'Link to',
        linkPlaceholder: 'Type to search: elements of this topic, keys, topics',
        linkWeb: 'Web address…',
        linkThisTopic: 'In this topic',
        linkKeys: 'Keys',
        linkTopics: 'Topics and maps',
        linkTopicItself: 'The topic itself',
        linkStepTwo: 'Link to {0}, or to one of its elements',
        linkWebPrompt: 'Web address (https://…, or mailto:…)',
        linkWebInvalid: 'Type an address starting with http://, https:// or mailto:',
        linkNotFound: 'Cannot find the link target: {0}',
        linkNotHere: 'A link cannot go here.',
        quickFix: 'Quick Fix…',
        quickFixes: 'Quick fixes (Ctrl+.)',
        noQuickFixes: 'No quick fixes available',
        quickFixStale: 'The document changed: try again.',
        quickFixFailed: 'The quick fix failed: {0}',
        noProblemHere: 'No problem at the cursor.',
        quickFixApplied: 'Fixed: {0}',
        openTarget: 'Open target',
        foldRow: 'Fold or unfold (Left/Right)',
        noTarget: 'no target',
        expandAll: 'Expand all',
        collapseAll: 'Collapse all',
        changeTarget: 'Change target…',
        addReference: 'Add reference…',
        addReferenceShort: 'Reference',
        editLabel: 'Edit label',
        labelHint: 'Navigation title (empty: the topic\'s title)',
        indentRow: 'Indent',
        outdentRow: 'Outdent',
        referenceNotHere: 'A reference cannot go here.',
        rowStale: 'The map changed: try again.',
        mapPickTitle: 'Reference to',
        mapPlaceholder: 'Type to search: keys, topics, maps',
        relTable: 'Relationship table',
        relTableShort: 'Relationships',
        insertRelTable: 'Insert relationship table',
        moveRowUp: 'Move row up',
        moveRowDown: 'Move row down',
        emptyCell: 'no references',
        anyType: 'any type',
        contextPickTitle: 'Map context',
        contextAutomatic: 'Automatic: the first map that references the topic',
        contextNone: 'No map context',
        contextNoneDetail: 'Keys from the nearest root map; nothing from a map',
        contextNoPlace: 'No map of the workspace references this topic',
        contextStatus: 'Map: {0}',
        contextExcluded: 'In this map, the filter {0} excludes this topic ({1})',
        chooseContext: 'Choose the map context (keys, metadata)',
    },
    domains: {
        topic: 'Base', map: 'Map', concept: 'Concept', task: 'Task', reference: 'Reference', glossentry: 'Glossary',
        glossgroup: 'Glossary', troubleshooting: 'Troubleshooting', 'hi-d': 'Highlighting', 'pr-d': 'Programming',
        'sw-d': 'Software', 'ui-d': 'User interface', 'ut-d': 'Utilities', 'indexing-d': 'Indexing',
        'hazard-d': 'Hazard statements', 'abbrev-d': 'Abbreviations', 'markup-d': 'Markup', 'xml-d': 'XML mentions',
        'equation-d': 'Equations', 'mathml-d': 'MathML', 'svg-d': 'SVG', 'relmgmt-d': 'Release management',
        'alternativeTitles-d': 'Alternative titles', 'emphasis-d': 'Emphasis', 'learning-d': 'Learning',
        'learningInteractionBase-d': 'Learning interactions', 'learningInteractionBase2-d': 'Learning interactions',
        'learning2-d': 'Learning', 'taskreq-d': 'Task requirements', 'delay-d': 'Delayed resolution', 'ditavalref-d': 'DITAVAL references',
        'mapgroup-d': 'Map groups', bookmap: 'Book',
    },
};

const FR: Partial<Labels> & { ui: Record<string, string> } = {
    note: {
        note: 'Remarque', tip: 'Conseil', fastpath: 'Accès rapide', restriction: 'Restriction', important: 'Important',
        remember: 'Rappel', attention: 'Attention', caution: 'ATTENTION', notice: 'AVIS', danger: 'DANGER',
        warning: 'AVERTISSEMENT', trouble: 'Incident', other: 'Remarque',
    },
    hazard: { danger: 'DANGER', warning: 'AVERTISSEMENT', caution: 'ATTENTION', notice: 'AVIS' },
    section: {
        prereq: 'Avant de commencer', context: 'À propos de cette tâche', result: 'Résultats', postreq: 'Étapes suivantes',
        tasktroubleshooting: 'Résolution des incidents', steptroubleshooting: 'Résolution des incidents',
        condition: 'Condition', cause: 'Cause', remedy: 'Solution', responsibleParty: 'Responsable',
    },
    figure: 'Figure {0}. ',
    table: 'Tableau {0}. ',
    relatedInformation: 'Informations connexes',
    footnotes: 'Notes de bas de page',
    optional: 'Facultatif : ',
    required: 'Obligatoire : ',
    option: 'Option',
    description: 'Description',
    type: 'Type',
    value: 'Valeur',
    ui: {
        problems: '{0} problèmes',
        oneProblem: '1 problème',
        noProblems: 'Aucun problème',
        fallbackGrammar: 'GRAMMAIRE DE SECOURS',
        waitingForXml: 'En attente d’un XML bien formé — ligne {0} : {1}',
        undeclaredEntities: '{0} entités non déclarées',
        filter: 'Filtre : {0}',
        noFilter: 'Aucun filtre',
        locked: 'Verrouillé sur cette rubrique',
        follow: 'Suit l’éditeur actif',
        showMarkup: 'Afficher le balisage',
        hideMarkup: 'Masquer le balisage',
        syncOn: 'Synchro : oui',
        syncOff: 'Synchro : non',
        theme: 'Thème : {0}',
        refresh: 'Actualiser',
        openSource: 'Ouvrir la source',
        previewDitaOt: 'Aperçu avec DITA-OT',
        lock: 'Verrouiller',
        unlock: 'Déverrouiller',
        ctrlClickToOpen: 'Ctrl+clic pour ouvrir',
        fromKey: 'Depuis la clé « {0} »',
        reusedFrom: 'Contenu réutilisé depuis {0}',
        unresolved: 'Non résolu : {0}',
        largeDocument: 'Document volumineux : les références ne sont pas résolues automatiquement.',
        emptyPreview: 'Ouvrez une rubrique DITA pour l’afficher.',
        mapNotSupported: 'Les cartes sont prévisualisées avec DITA-OT.',
        undo: 'Annuler',
        redo: 'Rétablir',
        style: 'Style',
        bold: 'Gras',
        italic: 'Italique',
        underline: 'Souligné',
        code: 'Code',
        superscript: 'Exposant',
        subscript: 'Indice',
        bulletList: 'Liste à puces',
        numberedList: 'Liste numérotée',
        indent: 'Augmenter le retrait',
        outdent: 'Diminuer le retrait',
        insert: 'Insérer',
        insertMore: 'Autres éléments',
        table: 'Tableau',
        insertTable: 'Insérer un tableau',
        rows: 'Lignes',
        rowAbove: 'Insérer une ligne au-dessus',
        rowBelow: 'Insérer une ligne en dessous',
        deleteRow: 'Supprimer la ligne',
        headerRow: 'Ligne d’en-tête oui/non',
        columns: 'Colonnes',
        columnLeft: 'Insérer une colonne à gauche',
        columnRight: 'Insérer une colonne à droite',
        deleteColumn: 'Supprimer la colonne',
        cells: 'Cellules',
        mergeRight: 'Fusionner avec la cellule de droite',
        mergeDown: 'Fusionner avec la cellule du dessous',
        splitCell: 'Fractionner la cellule',
        line: 'ligne {0}',
        nextProblem: 'Aller au problème suivant',
        reused: 'Contenu réutilisé',
        reuseOpen: 'Ouvrir la source réutilisée',
        replaceWithCopy: 'Remplacer par une copie',
        replaceWithCopyTitle: 'Copier ici le contenu réutilisé et supprimer la référence, pour le modifier dans cette rubrique seulement',
        reuseStale: 'Le document a changé : réessayez.',
        reuseFailed: 'Impossible d’utiliser le contenu réutilisé : {0}',
        reuseLost: 'L’élément réutilisé n’est plus là.',
        reuseNoFit: 'La copie ne peut pas être placée ici.',
        preview: 'Aperçu',
        saved: 'Toutes les modifications sont dans le document',
        writing: 'Écriture…',
        paused: 'XML mal formé — ligne {0} : {1}. Corrigez-le dans la source pour continuer.',
        readOnly: 'Lecture seule',
        notEditable: 'Conservé tel quel : modifiez-le dans la source',
        properties: 'Propriétés',
        propertiesEmpty: 'Placez le curseur dans une rubrique ou une carte DITA (éditeur texte ou visuel) pour voir les attributs de l’élément.',
        propertiesNotWellFormed: 'Le XML est mal formé ici : corrigez-le pour modifier les attributs.',
        groupIdentity: 'Identité et réutilisation',
        groupProfiling: 'Profilage',
        groupCommon: 'Communs',
        groupElement: 'Élément',
        groupArchitecture: 'Architecture',
        notSet: '— non défini —',
        defaultValue: 'par défaut : {0}',
        requiredField: 'obligatoire',
        fixedField: 'fixe',
        undeclared: 'non déclaré par le type de document',
        remove: 'Supprimer',
        formattingNoAttributes: 'La mise en forme (gras, italique…) ne porte pas d’attributs ici. Sélectionnez l’élément englobant.',
        readOnlyDocument: 'Ce document est en lecture seule.',
        documentChanged: 'Le document a changé : vérifiez et réessayez.',
        cut: 'Couper',
        copy: 'Copier',
        paste: 'Coller',
        insertAfter: 'Insérer après',
        insertInline: 'Insérer en ligne',
        wrapIn: 'Envelopper dans',
        changeTo: 'Transformer en',
        common: 'Courants',
        allElements: 'Tous les éléments',
        selectElement: 'Sélectionner',
        moveUp: 'Monter',
        moveDown: 'Descendre',
        unwrapElement: 'Retirer les balises (garder le contenu)',
        deleteElement: 'Supprimer',
        attributes: 'Attributs…',
        showInSource: 'Afficher dans la source',
        pasteFailed: 'Impossible de lire le presse-papiers ici : utilisez Ctrl+V.',
        image: 'Image',
        imageInText: 'Dans le texte…',
        imageOwnLine: 'Sur sa propre ligne…',
        imageInFigure: 'Dans une figure…',
        replaceImage: 'Remplacer l’image…',
        altText: 'Texte de remplacement…',
        imageAltPrompt: 'Texte de remplacement de l’image (lu à voix haute, et affiché quand l’image ne peut pas l’être)',
        imageAltPlaceholder: 'Décrivez l’image — laissez vide pour une image décorative',
        imagePickTitle: 'Insérer une image',
        imageReplaceTitle: 'Remplacer l’image',
        imagePickLabel: 'Choisir',
        imageFilter: 'Images',
        imageSaved: 'Image enregistrée : {0}',
        imageNotHere: 'Une image ne peut pas être placée ici.',
        imageFailed: 'Impossible d’insérer l’image : {0}',
        link: 'Lien…',
        changeLink: 'Changer la cible du lien…',
        openLink: 'Ouvrir la cible du lien',
        removeLink: 'Supprimer le lien',
        linkPickTitle: 'Lier à',
        linkPlaceholder: 'Tapez pour chercher : éléments de cette rubrique, clés, rubriques',
        linkWeb: 'Adresse web…',
        linkThisTopic: 'Dans cette rubrique',
        linkKeys: 'Clés',
        linkTopics: 'Rubriques et cartes',
        linkTopicItself: 'La rubrique elle-même',
        linkStepTwo: 'Lier à {0}, ou à l’un de ses éléments',
        linkWebPrompt: 'Adresse web (https://…, ou mailto:…)',
        linkWebInvalid: 'Tapez une adresse commençant par http://, https:// ou mailto:',
        linkNotFound: 'Cible du lien introuvable : {0}',
        linkNotHere: 'Un lien ne peut pas être placé ici.',
        quickFix: 'Correction rapide…',
        quickFixes: 'Corrections rapides (Ctrl+.)',
        noQuickFixes: 'Aucune correction rapide disponible',
        quickFixStale: 'Le document a changé : réessayez.',
        quickFixFailed: 'La correction rapide a échoué : {0}',
        noProblemHere: 'Aucun problème au curseur.',
        quickFixApplied: 'Corrigé : {0}',
        openTarget: 'Ouvrir la cible',
        foldRow: 'Replier ou déplier (Gauche/Droite)',
        noTarget: 'sans cible',
        expandAll: 'Tout déplier',
        collapseAll: 'Tout replier',
        changeTarget: 'Changer la cible…',
        addReference: 'Ajouter une référence…',
        addReferenceShort: 'Référence',
        editLabel: 'Modifier le libellé',
        labelHint: 'Titre de navigation (vide : le titre de la rubrique)',
        indentRow: 'Décaler à droite',
        outdentRow: 'Décaler à gauche',
        referenceNotHere: 'Une référence ne peut pas être placée ici.',
        rowStale: 'La carte a changé : réessayez.',
        mapPickTitle: 'Référence à',
        mapPlaceholder: 'Tapez pour chercher : clés, rubriques, cartes',
        relTable: 'Table de relations',
        relTableShort: 'Relations',
        insertRelTable: 'Insérer une table de relations',
        moveRowUp: 'Monter la ligne',
        moveRowDown: 'Descendre la ligne',
        emptyCell: 'aucune référence',
        anyType: 'tout type',
        contextPickTitle: 'Contexte de carte',
        contextAutomatic: 'Automatique : la première carte qui référence la rubrique',
        contextNone: 'Aucun contexte de carte',
        contextNoneDetail: 'Clés de la carte racine la plus proche ; rien d\'une carte',
        contextNoPlace: 'Aucune carte de l\'espace de travail ne référence cette rubrique',
        contextStatus: 'Carte : {0}',
        contextExcluded: 'Dans cette carte, le filtre {0} exclut cette rubrique ({1})',
        chooseContext: 'Choisir le contexte de carte (clés, métadonnées)',
    },
    domains: {
        topic: 'Base', map: 'Carte', concept: 'Concept', task: 'Tâche', reference: 'Référence', glossentry: 'Glossaire',
        glossgroup: 'Glossaire', troubleshooting: 'Dépannage', 'hi-d': 'Mise en évidence', 'pr-d': 'Programmation',
        'sw-d': 'Logiciel', 'ui-d': 'Interface utilisateur', 'ut-d': 'Utilitaires', 'indexing-d': 'Index',
        'hazard-d': 'Mises en garde', 'abbrev-d': 'Abréviations', 'markup-d': 'Balisage', 'xml-d': 'Mentions XML',
        'equation-d': 'Équations', 'mathml-d': 'MathML', 'svg-d': 'SVG', 'relmgmt-d': 'Gestion des versions',
        'alternativeTitles-d': 'Titres alternatifs', 'emphasis-d': 'Emphase', 'learning-d': 'Formation',
        'learningInteractionBase-d': 'Interactions de formation', 'learningInteractionBase2-d': 'Interactions de formation',
        'learning2-d': 'Formation', 'taskreq-d': 'Prérequis de tâche', 'delay-d': 'Résolution différée', 'ditavalref-d': 'Références DITAVAL',
        'mapgroup-d': 'Groupes de carte', bookmap: 'Livre',
    },
};

const BUNDLES: Record<string, Partial<Labels> & { ui?: Record<string, string> }> = { en: EN, fr: FR };

/** Labels for a VS Code / BCP 47 locale ("fr", "fr-CA", "en-US"…), English fallback per key. */
export function labelsFor(locale: string | undefined): Labels {
    const lang = (locale ?? 'en').split(/[-_]/)[0].toLowerCase();
    const bundle = BUNDLES[lang];
    if (!bundle || bundle === EN) {
        return EN;
    }
    return {
        ...EN,
        ...bundle,
        note: { ...EN.note, ...bundle.note },
        hazard: { ...EN.hazard, ...bundle.hazard },
        section: { ...EN.section, ...bundle.section },
        ui: { ...EN.ui, ...bundle.ui },
        domains: { ...EN.domains, ...bundle.domains },
    };
}

/** Replace {0}, {1}… placeholders. */
export function format(template: string, ...args: (string | number)[]): string {
    return template.replace(/\{(\d+)\}/g, (whole, i: string) => (args[Number(i)] !== undefined ? String(args[Number(i)]) : whole));
}
